export enum ExceptionEnum {
  NOT_FOUND_ERROR = 'NOT_FOUND_ERROR',
  REPOSITORY_ERROR = 'REPOSITORY_ERROR',
  UPDATE_READONLY_RESOURCE = 'UPDATE_READONLY_RESOURCE',
  DELETE_READONLY_RESOURCE = 'DELETE_READONLY_RESOURCE',
}
