version: "2.3"
services:
  users:
    build:
      context: "${HOOMA_MS_USERS_BASE_PATH:-$PWD}"
      dockerfile: "./docker/images/users/Dockerfile"
    image: practice-hooma-users:latest
    expose:
      - 3000
    volumes:
      - /etc/localtime:/etc/localtime:ro
    restart: "always"
