version: "3.3"
services:
  users:
    environment:
      - DB_PG_PASSWORD_FILE=/run/secrets/db_password
      - JWT_PUBLIC_KEY_FILE=/run/secrets/jwt_public_key
    secrets:
      - db_password
      - jwt_public_key
