FROM node:18-alpine3.16

RUN apk add --no-cache curl su-exec bash protoc git

COPY ./docker/images/users/docker-entrypoint.sh /usr/local/bin/

ENTRYPOINT ["/usr/local/bin/docker-entrypoint.sh"]

CMD ["node"]
